
services:
  db:
    container_name: user_management_db
    image: postgres:latest
    restart: always
    env_file: .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data_user_management_app:/var/lib/postgresql/data

volumes:
  postgres_data_user_management_app:
      
      
    
    